-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity honeybee is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    edge_p1_x : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_p1_y : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_p1_z : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_p2_x : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_p2_y : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_p2_z : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of honeybee is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "honeybee,hls_ip_2019_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=637,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=48,HLS_SYN_FF=17318,HLS_SYN_LUT=29140,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_40000000 : STD_LOGIC_VECTOR (31 downto 0) := "01000000000000000000000000000000";
    constant ap_const_lv32_40400000 : STD_LOGIC_VECTOR (31 downto 0) := "01000000010000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zext_ln73_fu_220_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal k_fu_231_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_453 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_fu_237_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal b_reg_458 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_209_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grid_z_reg_463 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln74_fu_243_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal j_fu_254_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_reg_479 : STD_LOGIC_VECTOR (2 downto 0);
    signal grid_y_reg_484 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_lineIntersectGrid_fu_153_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_lineIntersectGrid_fu_153_ap_ready : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_153_ap_done : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_167_ap_ready : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_167_ap_done : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_181_ap_ready : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_181_ap_done : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_195_ap_ready : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_195_ap_done : STD_LOGIC;
    signal ap_block_state15_on_subcall_done : BOOLEAN;
    signal trunc_ln74_fu_260_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln74_reg_497 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln82_fu_264_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln82_reg_502 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_lineIntersectGrid_fu_167_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_1_reg_507 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln82_2_fu_274_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln82_2_reg_512 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_lineIntersectGrid_fu_181_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_2_reg_517 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_lineIntersectGrid_fu_195_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_3_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln82_fu_280_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_lineIntersectGrid_fu_153_ap_start : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_153_ap_idle : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_167_ap_start : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_167_ap_idle : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_181_ap_start : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_181_ap_idle : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_195_ap_start : STD_LOGIC;
    signal grp_lineIntersectGrid_fu_195_ap_idle : STD_LOGIC;
    signal k_0_reg_108 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln74_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_0_reg_119 : STD_LOGIC_VECTOR (6 downto 0);
    signal j_0_reg_131 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_reg_142 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_lineIntersectGrid_fu_153_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_lineIntersectGrid_fu_167_ap_start_reg : STD_LOGIC := '0';
    signal grp_lineIntersectGrid_fu_181_ap_start_reg : STD_LOGIC := '0';
    signal grp_lineIntersectGrid_fu_195_ap_start_reg : STD_LOGIC := '0';
    signal collisions_0_fu_68 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln79_3_fu_379_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln73_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_209_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln82_fu_270_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln74_1_fu_286_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln80_fu_290_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln82_1_fu_303_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln80_1_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln82_2_fu_319_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln80_2_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln82_1_fu_335_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln82_3_fu_340_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln80_3_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln79_fu_296_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln79_1_fu_312_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln79_2_fu_328_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln79_3_fu_350_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln79_1_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln79_fu_357_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln79_2_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln79_fu_375_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);

    component lineIntersectGrid IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        grid_x : IN STD_LOGIC_VECTOR (31 downto 0);
        grid_y : IN STD_LOGIC_VECTOR (31 downto 0);
        grid_z : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p1_x : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p1_y : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p1_z : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p2_x : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p2_y : IN STD_LOGIC_VECTOR (31 downto 0);
        edge_p2_z : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component honeybee_sitofp_3fYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_lineIntersectGrid_fu_153 : component lineIntersectGrid
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lineIntersectGrid_fu_153_ap_start,
        ap_done => grp_lineIntersectGrid_fu_153_ap_done,
        ap_idle => grp_lineIntersectGrid_fu_153_ap_idle,
        ap_ready => grp_lineIntersectGrid_fu_153_ap_ready,
        grid_x => ap_const_lv32_0,
        grid_y => grid_y_reg_484,
        grid_z => grid_z_reg_463,
        edge_p1_x => edge_p1_x,
        edge_p1_y => edge_p1_y,
        edge_p1_z => edge_p1_z,
        edge_p2_x => edge_p2_x,
        edge_p2_y => edge_p2_y,
        edge_p2_z => edge_p2_z,
        ap_return => grp_lineIntersectGrid_fu_153_ap_return);

    grp_lineIntersectGrid_fu_167 : component lineIntersectGrid
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lineIntersectGrid_fu_167_ap_start,
        ap_done => grp_lineIntersectGrid_fu_167_ap_done,
        ap_idle => grp_lineIntersectGrid_fu_167_ap_idle,
        ap_ready => grp_lineIntersectGrid_fu_167_ap_ready,
        grid_x => ap_const_lv32_3F800000,
        grid_y => grid_y_reg_484,
        grid_z => grid_z_reg_463,
        edge_p1_x => edge_p1_x,
        edge_p1_y => edge_p1_y,
        edge_p1_z => edge_p1_z,
        edge_p2_x => edge_p2_x,
        edge_p2_y => edge_p2_y,
        edge_p2_z => edge_p2_z,
        ap_return => grp_lineIntersectGrid_fu_167_ap_return);

    grp_lineIntersectGrid_fu_181 : component lineIntersectGrid
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lineIntersectGrid_fu_181_ap_start,
        ap_done => grp_lineIntersectGrid_fu_181_ap_done,
        ap_idle => grp_lineIntersectGrid_fu_181_ap_idle,
        ap_ready => grp_lineIntersectGrid_fu_181_ap_ready,
        grid_x => ap_const_lv32_40000000,
        grid_y => grid_y_reg_484,
        grid_z => grid_z_reg_463,
        edge_p1_x => edge_p1_x,
        edge_p1_y => edge_p1_y,
        edge_p1_z => edge_p1_z,
        edge_p2_x => edge_p2_x,
        edge_p2_y => edge_p2_y,
        edge_p2_z => edge_p2_z,
        ap_return => grp_lineIntersectGrid_fu_181_ap_return);

    grp_lineIntersectGrid_fu_195 : component lineIntersectGrid
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lineIntersectGrid_fu_195_ap_start,
        ap_done => grp_lineIntersectGrid_fu_195_ap_done,
        ap_idle => grp_lineIntersectGrid_fu_195_ap_idle,
        ap_ready => grp_lineIntersectGrid_fu_195_ap_ready,
        grid_x => ap_const_lv32_40400000,
        grid_y => grid_y_reg_484,
        grid_z => grid_z_reg_463,
        edge_p1_x => edge_p1_x,
        edge_p1_y => edge_p1_y,
        edge_p1_z => edge_p1_z,
        edge_p2_x => edge_p2_x,
        edge_p2_y => edge_p2_y,
        edge_p2_z => edge_p2_z,
        ap_return => grp_lineIntersectGrid_fu_195_ap_return);

    honeybee_sitofp_3fYi_U26 : component honeybee_sitofp_3fYi
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_209_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_209_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_lineIntersectGrid_fu_153_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lineIntersectGrid_fu_153_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_lineIntersectGrid_fu_153_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lineIntersectGrid_fu_153_ap_ready = ap_const_logic_1)) then 
                    grp_lineIntersectGrid_fu_153_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lineIntersectGrid_fu_167_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lineIntersectGrid_fu_167_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_lineIntersectGrid_fu_167_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lineIntersectGrid_fu_167_ap_ready = ap_const_logic_1)) then 
                    grp_lineIntersectGrid_fu_167_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lineIntersectGrid_fu_181_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lineIntersectGrid_fu_181_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_lineIntersectGrid_fu_181_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lineIntersectGrid_fu_181_ap_ready = ap_const_logic_1)) then 
                    grp_lineIntersectGrid_fu_181_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lineIntersectGrid_fu_195_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lineIntersectGrid_fu_195_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_lineIntersectGrid_fu_195_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lineIntersectGrid_fu_195_ap_ready = ap_const_logic_1)) then 
                    grp_lineIntersectGrid_fu_195_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    b_0_reg_119_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln74_fu_248_p2 = ap_const_lv1_1))) then 
                b_0_reg_119 <= b_reg_458;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                b_0_reg_119 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    b_1_reg_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                b_1_reg_142 <= add_ln82_fu_280_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                b_1_reg_142 <= b_0_reg_119;
            end if; 
        end if;
    end process;

    collisions_0_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                collisions_0_fu_68 <= or_ln79_3_fu_379_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                collisions_0_fu_68 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    j_0_reg_131_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                j_0_reg_131 <= j_reg_479;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                j_0_reg_131 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    k_0_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln74_fu_248_p2 = ap_const_lv1_1))) then 
                k_0_reg_108 <= k_reg_453;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_0_reg_108 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (ap_const_boolean_0 = ap_block_state15_on_subcall_done))) then
                    add_ln82_2_reg_512(6 downto 1) <= add_ln82_2_fu_274_p2(6 downto 1);
                    or_ln82_reg_502(5 downto 1) <= or_ln82_fu_264_p2(5 downto 1);
                tmp_4_1_reg_507 <= grp_lineIntersectGrid_fu_167_ap_return;
                tmp_4_2_reg_517 <= grp_lineIntersectGrid_fu_181_ap_return;
                tmp_4_3_reg_522 <= grp_lineIntersectGrid_fu_195_ap_return;
                tmp_4_reg_492 <= grp_lineIntersectGrid_fu_153_ap_return;
                trunc_ln74_reg_497 <= trunc_ln74_fu_260_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                b_reg_458 <= b_fu_237_p2;
                grid_z_reg_463 <= grp_fu_209_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                grid_y_reg_484 <= grp_fu_209_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                j_reg_479 <= j_fu_254_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                k_reg_453 <= k_fu_231_p2;
            end if;
        end if;
    end process;
    or_ln82_reg_502(0) <= '1';
    add_ln82_2_reg_512(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state8, ap_CS_fsm_state15, ap_block_state15_on_subcall_done, icmp_ln74_fu_248_p2, icmp_ln73_fu_225_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln73_fu_225_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln74_fu_248_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (ap_const_boolean_0 = ap_block_state15_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln82_2_fu_274_p2 <= std_logic_vector(unsigned(ap_const_lv7_1) + unsigned(zext_ln82_fu_270_p1));
    add_ln82_fu_280_p2 <= std_logic_vector(unsigned(ap_const_lv7_4) + unsigned(b_1_reg_142));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_block_state15_on_subcall_done_assign_proc : process(grp_lineIntersectGrid_fu_153_ap_done, grp_lineIntersectGrid_fu_167_ap_done, grp_lineIntersectGrid_fu_181_ap_done, grp_lineIntersectGrid_fu_195_ap_done)
    begin
                ap_block_state15_on_subcall_done <= ((grp_lineIntersectGrid_fu_153_ap_done = ap_const_logic_0) or (grp_lineIntersectGrid_fu_195_ap_done = ap_const_logic_0) or (grp_lineIntersectGrid_fu_181_ap_done = ap_const_logic_0) or (grp_lineIntersectGrid_fu_167_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln73_fu_225_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln73_fu_225_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln73_fu_225_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln73_fu_225_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= collisions_0_fu_68;
    b_fu_237_p2 <= std_logic_vector(unsigned(b_0_reg_119) + unsigned(ap_const_lv7_10));

    grp_fu_209_p0_assign_proc : process(zext_ln73_fu_220_p1, ap_CS_fsm_state2, zext_ln74_fu_243_p1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_209_p0 <= zext_ln74_fu_243_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_209_p0 <= zext_ln73_fu_220_p1;
        else 
            grp_fu_209_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_lineIntersectGrid_fu_153_ap_start <= grp_lineIntersectGrid_fu_153_ap_start_reg;
    grp_lineIntersectGrid_fu_167_ap_start <= grp_lineIntersectGrid_fu_167_ap_start_reg;
    grp_lineIntersectGrid_fu_181_ap_start <= grp_lineIntersectGrid_fu_181_ap_start_reg;
    grp_lineIntersectGrid_fu_195_ap_start <= grp_lineIntersectGrid_fu_195_ap_start_reg;
    icmp_ln73_fu_225_p2 <= "1" when (k_0_reg_108 = ap_const_lv3_4) else "0";
    icmp_ln74_fu_248_p2 <= "1" when (j_0_reg_131 = ap_const_lv3_4) else "0";
    j_fu_254_p2 <= std_logic_vector(unsigned(j_0_reg_131) + unsigned(ap_const_lv3_1));
    k_fu_231_p2 <= std_logic_vector(unsigned(k_0_reg_108) + unsigned(ap_const_lv3_1));
    or_ln79_1_fu_363_p2 <= (select_ln79_3_fu_350_p3 or select_ln79_2_fu_328_p3);
    or_ln79_2_fu_369_p2 <= (or_ln79_fu_357_p2 or or_ln79_1_fu_363_p2);
    or_ln79_3_fu_379_p2 <= (sext_ln79_fu_375_p1 or collisions_0_fu_68);
    or_ln79_fu_357_p2 <= (select_ln79_fu_296_p3 or select_ln79_1_fu_312_p3);
    or_ln82_1_fu_335_p2 <= (trunc_ln74_reg_497 or ap_const_lv6_3);
    or_ln82_fu_264_p2 <= (trunc_ln74_fu_260_p1 or ap_const_lv6_1);
    select_ln79_1_fu_312_p3 <= 
        shl_ln80_1_fu_306_p2 when (tmp_4_1_reg_507(0) = '1') else 
        ap_const_lv32_0;
    select_ln79_2_fu_328_p3 <= 
        shl_ln80_2_fu_322_p2 when (tmp_4_2_reg_517(0) = '1') else 
        ap_const_lv32_0;
    select_ln79_3_fu_350_p3 <= 
        shl_ln80_3_fu_344_p2 when (tmp_4_3_reg_522(0) = '1') else 
        ap_const_lv32_0;
    select_ln79_fu_296_p3 <= 
        shl_ln80_fu_290_p2 when (tmp_4_reg_492(0) = '1') else 
        ap_const_lv32_0;
        sext_ln79_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln79_2_fu_369_p2),64));

    shl_ln80_1_fu_306_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln82_1_fu_303_p1(31-1 downto 0)))));
    shl_ln80_2_fu_322_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln82_2_fu_319_p1(31-1 downto 0)))));
    shl_ln80_3_fu_344_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln82_3_fu_340_p1(31-1 downto 0)))));
    shl_ln80_fu_290_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln74_1_fu_286_p1(31-1 downto 0)))));
    trunc_ln74_fu_260_p1 <= b_1_reg_142(6 - 1 downto 0);
    zext_ln73_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_108),32));
    zext_ln74_1_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_1_reg_142),32));
    zext_ln74_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_131),32));
    zext_ln82_1_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln82_reg_502),32));
    zext_ln82_2_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln82_2_reg_512),32));
    zext_ln82_3_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln82_1_fu_335_p2),32));
    zext_ln82_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln82_fu_264_p2),7));
end behav;
