// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "honeybee.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic honeybee::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic honeybee::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> honeybee::ap_ST_fsm_state1 = "1";
const sc_lv<8> honeybee::ap_ST_fsm_state2 = "10";
const sc_lv<8> honeybee::ap_ST_fsm_state3 = "100";
const sc_lv<8> honeybee::ap_ST_fsm_state4 = "1000";
const sc_lv<8> honeybee::ap_ST_fsm_state5 = "10000";
const sc_lv<8> honeybee::ap_ST_fsm_state6 = "100000";
const sc_lv<8> honeybee::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> honeybee::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> honeybee::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> honeybee::ap_const_lv32_1 = "1";
const sc_lv<32> honeybee::ap_const_lv32_4 = "100";
const sc_lv<32> honeybee::ap_const_lv32_6 = "110";
const bool honeybee::ap_const_boolean_0 = false;
const sc_lv<32> honeybee::ap_const_lv32_7 = "111";
const sc_lv<3> honeybee::ap_const_lv3_0 = "000";
const sc_lv<7> honeybee::ap_const_lv7_0 = "0000000";
const sc_lv<64> honeybee::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> honeybee::ap_const_lv32_5 = "101";
const sc_lv<32> honeybee::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> honeybee::ap_const_lv32_40000000 = "1000000000000000000000000000000";
const sc_lv<32> honeybee::ap_const_lv32_40400000 = "1000000010000000000000000000000";
const sc_lv<3> honeybee::ap_const_lv3_4 = "100";
const sc_lv<3> honeybee::ap_const_lv3_1 = "1";
const sc_lv<6> honeybee::ap_const_lv6_1 = "1";
const sc_lv<7> honeybee::ap_const_lv7_1 = "1";
const sc_lv<7> honeybee::ap_const_lv7_10 = "10000";
const sc_lv<6> honeybee::ap_const_lv6_4 = "100";
const sc_lv<6> honeybee::ap_const_lv6_3 = "11";
const sc_lv<7> honeybee::ap_const_lv7_4 = "100";
const sc_lv<6> honeybee::ap_const_lv6_5 = "101";
const sc_lv<6> honeybee::ap_const_lv6_7 = "111";
const sc_lv<6> honeybee::ap_const_lv6_C = "1100";
const sc_lv<7> honeybee::ap_const_lv7_5 = "101";
const sc_lv<7> honeybee::ap_const_lv7_6 = "110";
const sc_lv<7> honeybee::ap_const_lv7_7 = "111";
const sc_lv<6> honeybee::ap_const_lv6_D = "1101";
const sc_lv<6> honeybee::ap_const_lv6_F = "1111";
const sc_lv<1> honeybee::ap_const_lv1_1 = "1";
const bool honeybee::ap_const_boolean_1 = true;

honeybee::honeybee(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_segmentIntersectsGri_fu_151 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_151");
    grp_segmentIntersectsGri_fu_151->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_151->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_151->ap_start(grp_segmentIntersectsGri_fu_151_ap_start);
    grp_segmentIntersectsGri_fu_151->ap_done(grp_segmentIntersectsGri_fu_151_ap_done);
    grp_segmentIntersectsGri_fu_151->ap_idle(grp_segmentIntersectsGri_fu_151_ap_idle);
    grp_segmentIntersectsGri_fu_151->ap_ready(grp_segmentIntersectsGri_fu_151_ap_ready);
    grp_segmentIntersectsGri_fu_151->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_151->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_151->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_151->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_151->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_151->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_151->grid_x(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_151->grid_y(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_151->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_151->ap_return(grp_segmentIntersectsGri_fu_151_ap_return);
    grp_segmentIntersectsGri_fu_166 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_166");
    grp_segmentIntersectsGri_fu_166->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_166->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_166->ap_start(grp_segmentIntersectsGri_fu_166_ap_start);
    grp_segmentIntersectsGri_fu_166->ap_done(grp_segmentIntersectsGri_fu_166_ap_done);
    grp_segmentIntersectsGri_fu_166->ap_idle(grp_segmentIntersectsGri_fu_166_ap_idle);
    grp_segmentIntersectsGri_fu_166->ap_ready(grp_segmentIntersectsGri_fu_166_ap_ready);
    grp_segmentIntersectsGri_fu_166->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_166->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_166->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_166->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_166->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_166->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_166->grid_x(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_166->grid_y(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_166->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_166->ap_return(grp_segmentIntersectsGri_fu_166_ap_return);
    grp_segmentIntersectsGri_fu_181 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_181");
    grp_segmentIntersectsGri_fu_181->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_181->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_181->ap_start(grp_segmentIntersectsGri_fu_181_ap_start);
    grp_segmentIntersectsGri_fu_181->ap_done(grp_segmentIntersectsGri_fu_181_ap_done);
    grp_segmentIntersectsGri_fu_181->ap_idle(grp_segmentIntersectsGri_fu_181_ap_idle);
    grp_segmentIntersectsGri_fu_181->ap_ready(grp_segmentIntersectsGri_fu_181_ap_ready);
    grp_segmentIntersectsGri_fu_181->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_181->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_181->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_181->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_181->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_181->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_181->grid_x(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_181->grid_y(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_181->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_181->ap_return(grp_segmentIntersectsGri_fu_181_ap_return);
    grp_segmentIntersectsGri_fu_196 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_196");
    grp_segmentIntersectsGri_fu_196->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_196->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_196->ap_start(grp_segmentIntersectsGri_fu_196_ap_start);
    grp_segmentIntersectsGri_fu_196->ap_done(grp_segmentIntersectsGri_fu_196_ap_done);
    grp_segmentIntersectsGri_fu_196->ap_idle(grp_segmentIntersectsGri_fu_196_ap_idle);
    grp_segmentIntersectsGri_fu_196->ap_ready(grp_segmentIntersectsGri_fu_196_ap_ready);
    grp_segmentIntersectsGri_fu_196->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_196->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_196->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_196->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_196->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_196->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_196->grid_x(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_196->grid_y(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_196->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_196->ap_return(grp_segmentIntersectsGri_fu_196_ap_return);
    grp_segmentIntersectsGri_fu_211 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_211");
    grp_segmentIntersectsGri_fu_211->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_211->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_211->ap_start(grp_segmentIntersectsGri_fu_211_ap_start);
    grp_segmentIntersectsGri_fu_211->ap_done(grp_segmentIntersectsGri_fu_211_ap_done);
    grp_segmentIntersectsGri_fu_211->ap_idle(grp_segmentIntersectsGri_fu_211_ap_idle);
    grp_segmentIntersectsGri_fu_211->ap_ready(grp_segmentIntersectsGri_fu_211_ap_ready);
    grp_segmentIntersectsGri_fu_211->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_211->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_211->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_211->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_211->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_211->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_211->grid_x(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_211->grid_y(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_211->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_211->ap_return(grp_segmentIntersectsGri_fu_211_ap_return);
    grp_segmentIntersectsGri_fu_226 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_226");
    grp_segmentIntersectsGri_fu_226->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_226->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_226->ap_start(grp_segmentIntersectsGri_fu_226_ap_start);
    grp_segmentIntersectsGri_fu_226->ap_done(grp_segmentIntersectsGri_fu_226_ap_done);
    grp_segmentIntersectsGri_fu_226->ap_idle(grp_segmentIntersectsGri_fu_226_ap_idle);
    grp_segmentIntersectsGri_fu_226->ap_ready(grp_segmentIntersectsGri_fu_226_ap_ready);
    grp_segmentIntersectsGri_fu_226->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_226->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_226->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_226->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_226->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_226->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_226->grid_x(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_226->grid_y(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_226->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_226->ap_return(grp_segmentIntersectsGri_fu_226_ap_return);
    grp_segmentIntersectsGri_fu_241 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_241");
    grp_segmentIntersectsGri_fu_241->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_241->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_241->ap_start(grp_segmentIntersectsGri_fu_241_ap_start);
    grp_segmentIntersectsGri_fu_241->ap_done(grp_segmentIntersectsGri_fu_241_ap_done);
    grp_segmentIntersectsGri_fu_241->ap_idle(grp_segmentIntersectsGri_fu_241_ap_idle);
    grp_segmentIntersectsGri_fu_241->ap_ready(grp_segmentIntersectsGri_fu_241_ap_ready);
    grp_segmentIntersectsGri_fu_241->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_241->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_241->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_241->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_241->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_241->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_241->grid_x(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_241->grid_y(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_241->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_241->ap_return(grp_segmentIntersectsGri_fu_241_ap_return);
    grp_segmentIntersectsGri_fu_256 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_256");
    grp_segmentIntersectsGri_fu_256->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_256->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_256->ap_start(grp_segmentIntersectsGri_fu_256_ap_start);
    grp_segmentIntersectsGri_fu_256->ap_done(grp_segmentIntersectsGri_fu_256_ap_done);
    grp_segmentIntersectsGri_fu_256->ap_idle(grp_segmentIntersectsGri_fu_256_ap_idle);
    grp_segmentIntersectsGri_fu_256->ap_ready(grp_segmentIntersectsGri_fu_256_ap_ready);
    grp_segmentIntersectsGri_fu_256->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_256->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_256->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_256->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_256->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_256->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_256->grid_x(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_256->grid_y(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_256->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_256->ap_return(grp_segmentIntersectsGri_fu_256_ap_return);
    grp_segmentIntersectsGri_fu_271 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_271");
    grp_segmentIntersectsGri_fu_271->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_271->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_271->ap_start(grp_segmentIntersectsGri_fu_271_ap_start);
    grp_segmentIntersectsGri_fu_271->ap_done(grp_segmentIntersectsGri_fu_271_ap_done);
    grp_segmentIntersectsGri_fu_271->ap_idle(grp_segmentIntersectsGri_fu_271_ap_idle);
    grp_segmentIntersectsGri_fu_271->ap_ready(grp_segmentIntersectsGri_fu_271_ap_ready);
    grp_segmentIntersectsGri_fu_271->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_271->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_271->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_271->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_271->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_271->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_271->grid_x(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_271->grid_y(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_271->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_271->ap_return(grp_segmentIntersectsGri_fu_271_ap_return);
    grp_segmentIntersectsGri_fu_286 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_286");
    grp_segmentIntersectsGri_fu_286->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_286->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_286->ap_start(grp_segmentIntersectsGri_fu_286_ap_start);
    grp_segmentIntersectsGri_fu_286->ap_done(grp_segmentIntersectsGri_fu_286_ap_done);
    grp_segmentIntersectsGri_fu_286->ap_idle(grp_segmentIntersectsGri_fu_286_ap_idle);
    grp_segmentIntersectsGri_fu_286->ap_ready(grp_segmentIntersectsGri_fu_286_ap_ready);
    grp_segmentIntersectsGri_fu_286->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_286->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_286->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_286->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_286->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_286->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_286->grid_x(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_286->grid_y(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_286->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_286->ap_return(grp_segmentIntersectsGri_fu_286_ap_return);
    grp_segmentIntersectsGri_fu_301 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_301");
    grp_segmentIntersectsGri_fu_301->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_301->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_301->ap_start(grp_segmentIntersectsGri_fu_301_ap_start);
    grp_segmentIntersectsGri_fu_301->ap_done(grp_segmentIntersectsGri_fu_301_ap_done);
    grp_segmentIntersectsGri_fu_301->ap_idle(grp_segmentIntersectsGri_fu_301_ap_idle);
    grp_segmentIntersectsGri_fu_301->ap_ready(grp_segmentIntersectsGri_fu_301_ap_ready);
    grp_segmentIntersectsGri_fu_301->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_301->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_301->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_301->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_301->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_301->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_301->grid_x(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_301->grid_y(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_301->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_301->ap_return(grp_segmentIntersectsGri_fu_301_ap_return);
    grp_segmentIntersectsGri_fu_316 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_316");
    grp_segmentIntersectsGri_fu_316->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_316->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_316->ap_start(grp_segmentIntersectsGri_fu_316_ap_start);
    grp_segmentIntersectsGri_fu_316->ap_done(grp_segmentIntersectsGri_fu_316_ap_done);
    grp_segmentIntersectsGri_fu_316->ap_idle(grp_segmentIntersectsGri_fu_316_ap_idle);
    grp_segmentIntersectsGri_fu_316->ap_ready(grp_segmentIntersectsGri_fu_316_ap_ready);
    grp_segmentIntersectsGri_fu_316->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_316->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_316->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_316->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_316->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_316->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_316->grid_x(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_316->grid_y(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_316->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_316->ap_return(grp_segmentIntersectsGri_fu_316_ap_return);
    grp_segmentIntersectsGri_fu_331 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_331");
    grp_segmentIntersectsGri_fu_331->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_331->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_331->ap_start(grp_segmentIntersectsGri_fu_331_ap_start);
    grp_segmentIntersectsGri_fu_331->ap_done(grp_segmentIntersectsGri_fu_331_ap_done);
    grp_segmentIntersectsGri_fu_331->ap_idle(grp_segmentIntersectsGri_fu_331_ap_idle);
    grp_segmentIntersectsGri_fu_331->ap_ready(grp_segmentIntersectsGri_fu_331_ap_ready);
    grp_segmentIntersectsGri_fu_331->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_331->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_331->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_331->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_331->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_331->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_331->grid_x(ap_var_for_const0);
    grp_segmentIntersectsGri_fu_331->grid_y(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_331->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_331->ap_return(grp_segmentIntersectsGri_fu_331_ap_return);
    grp_segmentIntersectsGri_fu_346 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_346");
    grp_segmentIntersectsGri_fu_346->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_346->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_346->ap_start(grp_segmentIntersectsGri_fu_346_ap_start);
    grp_segmentIntersectsGri_fu_346->ap_done(grp_segmentIntersectsGri_fu_346_ap_done);
    grp_segmentIntersectsGri_fu_346->ap_idle(grp_segmentIntersectsGri_fu_346_ap_idle);
    grp_segmentIntersectsGri_fu_346->ap_ready(grp_segmentIntersectsGri_fu_346_ap_ready);
    grp_segmentIntersectsGri_fu_346->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_346->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_346->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_346->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_346->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_346->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_346->grid_x(ap_var_for_const1);
    grp_segmentIntersectsGri_fu_346->grid_y(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_346->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_346->ap_return(grp_segmentIntersectsGri_fu_346_ap_return);
    grp_segmentIntersectsGri_fu_361 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_361");
    grp_segmentIntersectsGri_fu_361->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_361->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_361->ap_start(grp_segmentIntersectsGri_fu_361_ap_start);
    grp_segmentIntersectsGri_fu_361->ap_done(grp_segmentIntersectsGri_fu_361_ap_done);
    grp_segmentIntersectsGri_fu_361->ap_idle(grp_segmentIntersectsGri_fu_361_ap_idle);
    grp_segmentIntersectsGri_fu_361->ap_ready(grp_segmentIntersectsGri_fu_361_ap_ready);
    grp_segmentIntersectsGri_fu_361->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_361->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_361->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_361->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_361->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_361->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_361->grid_x(ap_var_for_const2);
    grp_segmentIntersectsGri_fu_361->grid_y(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_361->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_361->ap_return(grp_segmentIntersectsGri_fu_361_ap_return);
    grp_segmentIntersectsGri_fu_376 = new segmentIntersectsGri("grp_segmentIntersectsGri_fu_376");
    grp_segmentIntersectsGri_fu_376->ap_clk(ap_clk);
    grp_segmentIntersectsGri_fu_376->ap_rst(ap_rst);
    grp_segmentIntersectsGri_fu_376->ap_start(grp_segmentIntersectsGri_fu_376_ap_start);
    grp_segmentIntersectsGri_fu_376->ap_done(grp_segmentIntersectsGri_fu_376_ap_done);
    grp_segmentIntersectsGri_fu_376->ap_idle(grp_segmentIntersectsGri_fu_376_ap_idle);
    grp_segmentIntersectsGri_fu_376->ap_ready(grp_segmentIntersectsGri_fu_376_ap_ready);
    grp_segmentIntersectsGri_fu_376->edge_p1_x(edge_p1_x);
    grp_segmentIntersectsGri_fu_376->edge_p1_y(edge_p1_y);
    grp_segmentIntersectsGri_fu_376->edge_p1_z(edge_p1_z);
    grp_segmentIntersectsGri_fu_376->edge_p2_x(edge_p2_x);
    grp_segmentIntersectsGri_fu_376->edge_p2_y(edge_p2_y);
    grp_segmentIntersectsGri_fu_376->edge_p2_z(edge_p2_z);
    grp_segmentIntersectsGri_fu_376->grid_x(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_376->grid_y(ap_var_for_const3);
    grp_segmentIntersectsGri_fu_376->grid_z(grid_z_reg_1023);
    grp_segmentIntersectsGri_fu_376->ap_return(grp_segmentIntersectsGri_fu_376_ap_return);
    honeybee_sitofp_3hbi_U62 = new honeybee_sitofp_3hbi<1,4,32,32>("honeybee_sitofp_3hbi_U62");
    honeybee_sitofp_3hbi_U62->clk(ap_clk);
    honeybee_sitofp_3hbi_U62->reset(ap_rst);
    honeybee_sitofp_3hbi_U62->din0(grp_fu_391_p0);
    honeybee_sitofp_3hbi_U62->ce(ap_var_for_const4);
    honeybee_sitofp_3hbi_U62->dout(grp_fu_391_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln164_1_fu_521_p2);
    sensitive << ( zext_ln164_fu_442_p1 );

    SC_METHOD(thread_add_ln164_2_fu_570_p2);
    sensitive << ( zext_ln164_7_fu_549_p1 );

    SC_METHOD(thread_add_ln164_3_fu_637_p2);
    sensitive << ( zext_ln164_fu_442_p1 );

    SC_METHOD(thread_add_ln164_4_fu_660_p2);
    sensitive << ( zext_ln164_fu_442_p1 );

    SC_METHOD(thread_add_ln164_5_fu_683_p2);
    sensitive << ( zext_ln164_fu_442_p1 );

    SC_METHOD(thread_add_ln164_6_fu_745_p2);
    sensitive << ( zext_ln164_15_fu_724_p1 );

    SC_METHOD(thread_add_ln164_fu_425_p2);
    sensitive << ( zext_ln164_2_fu_421_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state7_on_subcall_done);
    sensitive << ( grp_segmentIntersectsGri_fu_151_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_166_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_181_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_196_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_211_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_226_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_241_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_256_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_271_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_286_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_301_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_316_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_331_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_346_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_361_ap_done );
    sensitive << ( grp_segmentIntersectsGri_fu_376_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln155_fu_399_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln155_fu_399_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( collisions_0_reg_139 );
    sensitive << ( icmp_ln155_fu_399_p2 );

    SC_METHOD(thread_b_fu_431_p2);
    sensitive << ( b_0_reg_127 );

    SC_METHOD(thread_grp_fu_391_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( k_0_reg_116 );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_151_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_151_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_166_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_166_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_181_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_181_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_196_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_196_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_211_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_211_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_226_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_226_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_241_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_241_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_256_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_256_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_271_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_271_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_286_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_286_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_301_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_301_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_316_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_316_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_331_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_331_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_346_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_346_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_361_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_361_ap_start_reg );

    SC_METHOD(thread_grp_segmentIntersectsGri_fu_376_ap_start);
    sensitive << ( grp_segmentIntersectsGri_fu_376_ap_start_reg );

    SC_METHOD(thread_icmp_ln155_fu_399_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( k_0_reg_116 );

    SC_METHOD(thread_k_fu_405_p2);
    sensitive << ( k_0_reg_116 );

    SC_METHOD(thread_or_ln161_10_fu_850_p2);
    sensitive << ( select_ln161_12_fu_712_p3 );
    sensitive << ( select_ln161_13_fu_738_p3 );

    SC_METHOD(thread_or_ln161_11_fu_856_p2);
    sensitive << ( select_ln161_14_fu_761_p3 );
    sensitive << ( select_ln161_15_fu_783_p3 );

    SC_METHOD(thread_or_ln161_12_fu_862_p2);
    sensitive << ( or_ln161_11_fu_856_p2 );
    sensitive << ( or_ln161_10_fu_850_p2 );

    SC_METHOD(thread_or_ln161_13_fu_868_p2);
    sensitive << ( or_ln161_12_fu_862_p2 );
    sensitive << ( or_ln161_9_fu_844_p2 );

    SC_METHOD(thread_or_ln161_14_fu_874_p2);
    sensitive << ( or_ln161_13_fu_868_p2 );
    sensitive << ( or_ln161_6_fu_826_p2 );

    SC_METHOD(thread_or_ln161_15_fu_884_p2);
    sensitive << ( collisions_0_reg_139 );
    sensitive << ( sext_ln161_fu_880_p1 );

    SC_METHOD(thread_or_ln161_1_fu_796_p2);
    sensitive << ( select_ln161_2_fu_492_p3 );
    sensitive << ( select_ln161_3_fu_514_p3 );

    SC_METHOD(thread_or_ln161_2_fu_802_p2);
    sensitive << ( or_ln161_1_fu_796_p2 );
    sensitive << ( or_ln161_fu_790_p2 );

    SC_METHOD(thread_or_ln161_3_fu_808_p2);
    sensitive << ( select_ln161_4_fu_537_p3 );
    sensitive << ( select_ln161_5_fu_563_p3 );

    SC_METHOD(thread_or_ln161_4_fu_814_p2);
    sensitive << ( select_ln161_6_fu_586_p3 );
    sensitive << ( select_ln161_7_fu_608_p3 );

    SC_METHOD(thread_or_ln161_5_fu_820_p2);
    sensitive << ( or_ln161_4_fu_814_p2 );
    sensitive << ( or_ln161_3_fu_808_p2 );

    SC_METHOD(thread_or_ln161_6_fu_826_p2);
    sensitive << ( or_ln161_5_fu_820_p2 );
    sensitive << ( or_ln161_2_fu_802_p2 );

    SC_METHOD(thread_or_ln161_7_fu_832_p2);
    sensitive << ( select_ln161_8_fu_630_p3 );
    sensitive << ( select_ln161_9_fu_653_p3 );

    SC_METHOD(thread_or_ln161_8_fu_838_p2);
    sensitive << ( select_ln161_10_fu_676_p3 );
    sensitive << ( select_ln161_11_fu_699_p3 );

    SC_METHOD(thread_or_ln161_9_fu_844_p2);
    sensitive << ( or_ln161_8_fu_838_p2 );
    sensitive << ( or_ln161_7_fu_832_p2 );

    SC_METHOD(thread_or_ln161_fu_790_p2);
    sensitive << ( select_ln161_fu_460_p3 );
    sensitive << ( select_ln161_1_fu_476_p3 );

    SC_METHOD(thread_or_ln164_1_fu_415_p2);
    sensitive << ( trunc_ln155_fu_411_p1 );

    SC_METHOD(thread_or_ln164_2_fu_499_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_3_fu_544_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_4_fu_593_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_5_fu_615_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_6_fu_719_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_7_fu_768_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_or_ln164_fu_437_p2);
    sensitive << ( trunc_ln155_reg_1043 );

    SC_METHOD(thread_select_ln161_10_fu_676_p3);
    sensitive << ( tmp_41_2_2_reg_1114 );
    sensitive << ( shl_ln162_10_fu_670_p2 );

    SC_METHOD(thread_select_ln161_11_fu_699_p3);
    sensitive << ( tmp_41_2_3_reg_1119 );
    sensitive << ( shl_ln162_11_fu_693_p2 );

    SC_METHOD(thread_select_ln161_12_fu_712_p3);
    sensitive << ( tmp_41_3_reg_1124 );
    sensitive << ( shl_ln162_12_fu_706_p2 );

    SC_METHOD(thread_select_ln161_13_fu_738_p3);
    sensitive << ( tmp_41_3_1_reg_1129 );
    sensitive << ( shl_ln162_13_fu_732_p2 );

    SC_METHOD(thread_select_ln161_14_fu_761_p3);
    sensitive << ( tmp_41_3_2_reg_1134 );
    sensitive << ( shl_ln162_14_fu_755_p2 );

    SC_METHOD(thread_select_ln161_15_fu_783_p3);
    sensitive << ( tmp_41_3_3_reg_1139 );
    sensitive << ( shl_ln162_15_fu_777_p2 );

    SC_METHOD(thread_select_ln161_1_fu_476_p3);
    sensitive << ( tmp_41_0_1_reg_1064 );
    sensitive << ( shl_ln162_1_fu_470_p2 );

    SC_METHOD(thread_select_ln161_2_fu_492_p3);
    sensitive << ( tmp_41_0_2_reg_1074 );
    sensitive << ( shl_ln162_2_fu_486_p2 );

    SC_METHOD(thread_select_ln161_3_fu_514_p3);
    sensitive << ( tmp_41_0_3_reg_1079 );
    sensitive << ( shl_ln162_3_fu_508_p2 );

    SC_METHOD(thread_select_ln161_4_fu_537_p3);
    sensitive << ( tmp_41_1_reg_1084 );
    sensitive << ( shl_ln162_4_fu_531_p2 );

    SC_METHOD(thread_select_ln161_5_fu_563_p3);
    sensitive << ( tmp_41_1_1_reg_1089 );
    sensitive << ( shl_ln162_5_fu_557_p2 );

    SC_METHOD(thread_select_ln161_6_fu_586_p3);
    sensitive << ( tmp_41_1_2_reg_1094 );
    sensitive << ( shl_ln162_6_fu_580_p2 );

    SC_METHOD(thread_select_ln161_7_fu_608_p3);
    sensitive << ( tmp_41_1_3_reg_1099 );
    sensitive << ( shl_ln162_7_fu_602_p2 );

    SC_METHOD(thread_select_ln161_8_fu_630_p3);
    sensitive << ( tmp_41_2_reg_1104 );
    sensitive << ( shl_ln162_8_fu_624_p2 );

    SC_METHOD(thread_select_ln161_9_fu_653_p3);
    sensitive << ( tmp_41_2_1_reg_1109 );
    sensitive << ( shl_ln162_9_fu_647_p2 );

    SC_METHOD(thread_select_ln161_fu_460_p3);
    sensitive << ( tmp_s_reg_1054 );
    sensitive << ( shl_ln162_fu_454_p2 );

    SC_METHOD(thread_sext_ln161_fu_880_p1);
    sensitive << ( or_ln161_14_fu_874_p2 );

    SC_METHOD(thread_shl_ln162_10_fu_670_p2);
    sensitive << ( zext_ln164_13_fu_666_p1 );

    SC_METHOD(thread_shl_ln162_11_fu_693_p2);
    sensitive << ( zext_ln164_14_fu_689_p1 );

    SC_METHOD(thread_shl_ln162_12_fu_706_p2);
    sensitive << ( zext_ln164_11_fu_620_p1 );

    SC_METHOD(thread_shl_ln162_13_fu_732_p2);
    sensitive << ( zext_ln164_16_fu_728_p1 );

    SC_METHOD(thread_shl_ln162_14_fu_755_p2);
    sensitive << ( zext_ln164_17_fu_751_p1 );

    SC_METHOD(thread_shl_ln162_15_fu_777_p2);
    sensitive << ( zext_ln164_18_fu_773_p1 );

    SC_METHOD(thread_shl_ln162_1_fu_470_p2);
    sensitive << ( zext_ln164_3_fu_467_p1 );

    SC_METHOD(thread_shl_ln162_2_fu_486_p2);
    sensitive << ( zext_ln164_4_fu_483_p1 );

    SC_METHOD(thread_shl_ln162_3_fu_508_p2);
    sensitive << ( zext_ln164_5_fu_504_p1 );

    SC_METHOD(thread_shl_ln162_4_fu_531_p2);
    sensitive << ( zext_ln164_1_fu_446_p1 );

    SC_METHOD(thread_shl_ln162_5_fu_557_p2);
    sensitive << ( zext_ln164_8_fu_553_p1 );

    SC_METHOD(thread_shl_ln162_6_fu_580_p2);
    sensitive << ( zext_ln164_9_fu_576_p1 );

    SC_METHOD(thread_shl_ln162_7_fu_602_p2);
    sensitive << ( zext_ln164_10_fu_598_p1 );

    SC_METHOD(thread_shl_ln162_8_fu_624_p2);
    sensitive << ( zext_ln164_6_fu_527_p1 );

    SC_METHOD(thread_shl_ln162_9_fu_647_p2);
    sensitive << ( zext_ln164_12_fu_643_p1 );

    SC_METHOD(thread_shl_ln162_fu_454_p2);
    sensitive << ( zext_ln155_1_fu_450_p1 );

    SC_METHOD(thread_trunc_ln155_fu_411_p1);
    sensitive << ( b_0_reg_127 );

    SC_METHOD(thread_zext_ln155_1_fu_450_p1);
    sensitive << ( b_0_reg_127 );

    SC_METHOD(thread_zext_ln164_10_fu_598_p1);
    sensitive << ( or_ln164_4_fu_593_p2 );

    SC_METHOD(thread_zext_ln164_11_fu_620_p1);
    sensitive << ( or_ln164_5_fu_615_p2 );

    SC_METHOD(thread_zext_ln164_12_fu_643_p1);
    sensitive << ( add_ln164_3_fu_637_p2 );

    SC_METHOD(thread_zext_ln164_13_fu_666_p1);
    sensitive << ( add_ln164_4_fu_660_p2 );

    SC_METHOD(thread_zext_ln164_14_fu_689_p1);
    sensitive << ( add_ln164_5_fu_683_p2 );

    SC_METHOD(thread_zext_ln164_15_fu_724_p1);
    sensitive << ( or_ln164_6_fu_719_p2 );

    SC_METHOD(thread_zext_ln164_16_fu_728_p1);
    sensitive << ( or_ln164_6_fu_719_p2 );

    SC_METHOD(thread_zext_ln164_17_fu_751_p1);
    sensitive << ( add_ln164_6_fu_745_p2 );

    SC_METHOD(thread_zext_ln164_18_fu_773_p1);
    sensitive << ( or_ln164_7_fu_768_p2 );

    SC_METHOD(thread_zext_ln164_1_fu_446_p1);
    sensitive << ( or_ln164_fu_437_p2 );

    SC_METHOD(thread_zext_ln164_2_fu_421_p1);
    sensitive << ( or_ln164_1_fu_415_p2 );

    SC_METHOD(thread_zext_ln164_3_fu_467_p1);
    sensitive << ( or_ln164_1_reg_1059 );

    SC_METHOD(thread_zext_ln164_4_fu_483_p1);
    sensitive << ( add_ln164_reg_1069 );

    SC_METHOD(thread_zext_ln164_5_fu_504_p1);
    sensitive << ( or_ln164_2_fu_499_p2 );

    SC_METHOD(thread_zext_ln164_6_fu_527_p1);
    sensitive << ( add_ln164_1_fu_521_p2 );

    SC_METHOD(thread_zext_ln164_7_fu_549_p1);
    sensitive << ( or_ln164_3_fu_544_p2 );

    SC_METHOD(thread_zext_ln164_8_fu_553_p1);
    sensitive << ( or_ln164_3_fu_544_p2 );

    SC_METHOD(thread_zext_ln164_9_fu_576_p1);
    sensitive << ( add_ln164_2_fu_570_p2 );

    SC_METHOD(thread_zext_ln164_fu_442_p1);
    sensitive << ( or_ln164_fu_437_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );
    sensitive << ( icmp_ln155_fu_399_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    ap_CS_fsm = "00000001";
    grp_segmentIntersectsGri_fu_151_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_166_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_181_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_196_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_211_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_226_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_241_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_256_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_271_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_286_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_301_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_316_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_331_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_346_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_361_ap_start_reg = SC_LOGIC_0;
    grp_segmentIntersectsGri_fu_376_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "honeybee_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, edge_p1_x, "(port)edge_p1_x");
    sc_trace(mVcdFile, edge_p1_y, "(port)edge_p1_y");
    sc_trace(mVcdFile, edge_p1_z, "(port)edge_p1_z");
    sc_trace(mVcdFile, edge_p2_x, "(port)edge_p2_x");
    sc_trace(mVcdFile, edge_p2_y, "(port)edge_p2_y");
    sc_trace(mVcdFile, edge_p2_z, "(port)edge_p2_z");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, k_fu_405_p2, "k_fu_405_p2");
    sc_trace(mVcdFile, k_reg_1018, "k_reg_1018");
    sc_trace(mVcdFile, grp_fu_391_p1, "grp_fu_391_p1");
    sc_trace(mVcdFile, grid_z_reg_1023, "grid_z_reg_1023");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln155_fu_411_p1, "trunc_ln155_fu_411_p1");
    sc_trace(mVcdFile, trunc_ln155_reg_1043, "trunc_ln155_reg_1043");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_ready, "grp_segmentIntersectsGri_fu_151_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_done, "grp_segmentIntersectsGri_fu_151_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_ready, "grp_segmentIntersectsGri_fu_166_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_done, "grp_segmentIntersectsGri_fu_166_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_ready, "grp_segmentIntersectsGri_fu_181_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_done, "grp_segmentIntersectsGri_fu_181_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_ready, "grp_segmentIntersectsGri_fu_196_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_done, "grp_segmentIntersectsGri_fu_196_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_ready, "grp_segmentIntersectsGri_fu_211_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_done, "grp_segmentIntersectsGri_fu_211_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_ready, "grp_segmentIntersectsGri_fu_226_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_done, "grp_segmentIntersectsGri_fu_226_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_ready, "grp_segmentIntersectsGri_fu_241_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_done, "grp_segmentIntersectsGri_fu_241_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_ready, "grp_segmentIntersectsGri_fu_256_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_done, "grp_segmentIntersectsGri_fu_256_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_ready, "grp_segmentIntersectsGri_fu_271_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_done, "grp_segmentIntersectsGri_fu_271_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_ready, "grp_segmentIntersectsGri_fu_286_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_done, "grp_segmentIntersectsGri_fu_286_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_ready, "grp_segmentIntersectsGri_fu_301_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_done, "grp_segmentIntersectsGri_fu_301_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_ready, "grp_segmentIntersectsGri_fu_316_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_done, "grp_segmentIntersectsGri_fu_316_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_ready, "grp_segmentIntersectsGri_fu_331_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_done, "grp_segmentIntersectsGri_fu_331_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_ready, "grp_segmentIntersectsGri_fu_346_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_done, "grp_segmentIntersectsGri_fu_346_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_ready, "grp_segmentIntersectsGri_fu_361_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_done, "grp_segmentIntersectsGri_fu_361_ap_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_ready, "grp_segmentIntersectsGri_fu_376_ap_ready");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_done, "grp_segmentIntersectsGri_fu_376_ap_done");
    sc_trace(mVcdFile, ap_block_state7_on_subcall_done, "ap_block_state7_on_subcall_done");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_return, "grp_segmentIntersectsGri_fu_151_ap_return");
    sc_trace(mVcdFile, tmp_s_reg_1054, "tmp_s_reg_1054");
    sc_trace(mVcdFile, or_ln164_1_fu_415_p2, "or_ln164_1_fu_415_p2");
    sc_trace(mVcdFile, or_ln164_1_reg_1059, "or_ln164_1_reg_1059");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_return, "grp_segmentIntersectsGri_fu_166_ap_return");
    sc_trace(mVcdFile, tmp_41_0_1_reg_1064, "tmp_41_0_1_reg_1064");
    sc_trace(mVcdFile, add_ln164_fu_425_p2, "add_ln164_fu_425_p2");
    sc_trace(mVcdFile, add_ln164_reg_1069, "add_ln164_reg_1069");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_return, "grp_segmentIntersectsGri_fu_181_ap_return");
    sc_trace(mVcdFile, tmp_41_0_2_reg_1074, "tmp_41_0_2_reg_1074");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_return, "grp_segmentIntersectsGri_fu_196_ap_return");
    sc_trace(mVcdFile, tmp_41_0_3_reg_1079, "tmp_41_0_3_reg_1079");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_return, "grp_segmentIntersectsGri_fu_211_ap_return");
    sc_trace(mVcdFile, tmp_41_1_reg_1084, "tmp_41_1_reg_1084");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_return, "grp_segmentIntersectsGri_fu_226_ap_return");
    sc_trace(mVcdFile, tmp_41_1_1_reg_1089, "tmp_41_1_1_reg_1089");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_return, "grp_segmentIntersectsGri_fu_241_ap_return");
    sc_trace(mVcdFile, tmp_41_1_2_reg_1094, "tmp_41_1_2_reg_1094");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_return, "grp_segmentIntersectsGri_fu_256_ap_return");
    sc_trace(mVcdFile, tmp_41_1_3_reg_1099, "tmp_41_1_3_reg_1099");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_return, "grp_segmentIntersectsGri_fu_271_ap_return");
    sc_trace(mVcdFile, tmp_41_2_reg_1104, "tmp_41_2_reg_1104");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_return, "grp_segmentIntersectsGri_fu_286_ap_return");
    sc_trace(mVcdFile, tmp_41_2_1_reg_1109, "tmp_41_2_1_reg_1109");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_return, "grp_segmentIntersectsGri_fu_301_ap_return");
    sc_trace(mVcdFile, tmp_41_2_2_reg_1114, "tmp_41_2_2_reg_1114");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_return, "grp_segmentIntersectsGri_fu_316_ap_return");
    sc_trace(mVcdFile, tmp_41_2_3_reg_1119, "tmp_41_2_3_reg_1119");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_return, "grp_segmentIntersectsGri_fu_331_ap_return");
    sc_trace(mVcdFile, tmp_41_3_reg_1124, "tmp_41_3_reg_1124");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_return, "grp_segmentIntersectsGri_fu_346_ap_return");
    sc_trace(mVcdFile, tmp_41_3_1_reg_1129, "tmp_41_3_1_reg_1129");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_return, "grp_segmentIntersectsGri_fu_361_ap_return");
    sc_trace(mVcdFile, tmp_41_3_2_reg_1134, "tmp_41_3_2_reg_1134");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_return, "grp_segmentIntersectsGri_fu_376_ap_return");
    sc_trace(mVcdFile, tmp_41_3_3_reg_1139, "tmp_41_3_3_reg_1139");
    sc_trace(mVcdFile, b_fu_431_p2, "b_fu_431_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, or_ln161_15_fu_884_p2, "or_ln161_15_fu_884_p2");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_start, "grp_segmentIntersectsGri_fu_151_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_idle, "grp_segmentIntersectsGri_fu_151_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_start, "grp_segmentIntersectsGri_fu_166_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_idle, "grp_segmentIntersectsGri_fu_166_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_start, "grp_segmentIntersectsGri_fu_181_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_idle, "grp_segmentIntersectsGri_fu_181_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_start, "grp_segmentIntersectsGri_fu_196_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_idle, "grp_segmentIntersectsGri_fu_196_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_start, "grp_segmentIntersectsGri_fu_211_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_idle, "grp_segmentIntersectsGri_fu_211_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_start, "grp_segmentIntersectsGri_fu_226_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_idle, "grp_segmentIntersectsGri_fu_226_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_start, "grp_segmentIntersectsGri_fu_241_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_idle, "grp_segmentIntersectsGri_fu_241_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_start, "grp_segmentIntersectsGri_fu_256_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_idle, "grp_segmentIntersectsGri_fu_256_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_start, "grp_segmentIntersectsGri_fu_271_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_idle, "grp_segmentIntersectsGri_fu_271_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_start, "grp_segmentIntersectsGri_fu_286_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_idle, "grp_segmentIntersectsGri_fu_286_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_start, "grp_segmentIntersectsGri_fu_301_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_idle, "grp_segmentIntersectsGri_fu_301_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_start, "grp_segmentIntersectsGri_fu_316_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_idle, "grp_segmentIntersectsGri_fu_316_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_start, "grp_segmentIntersectsGri_fu_331_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_idle, "grp_segmentIntersectsGri_fu_331_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_start, "grp_segmentIntersectsGri_fu_346_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_idle, "grp_segmentIntersectsGri_fu_346_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_start, "grp_segmentIntersectsGri_fu_361_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_idle, "grp_segmentIntersectsGri_fu_361_ap_idle");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_start, "grp_segmentIntersectsGri_fu_376_ap_start");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_idle, "grp_segmentIntersectsGri_fu_376_ap_idle");
    sc_trace(mVcdFile, k_0_reg_116, "k_0_reg_116");
    sc_trace(mVcdFile, b_0_reg_127, "b_0_reg_127");
    sc_trace(mVcdFile, collisions_0_reg_139, "collisions_0_reg_139");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_151_ap_start_reg, "grp_segmentIntersectsGri_fu_151_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_166_ap_start_reg, "grp_segmentIntersectsGri_fu_166_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_181_ap_start_reg, "grp_segmentIntersectsGri_fu_181_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_196_ap_start_reg, "grp_segmentIntersectsGri_fu_196_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_211_ap_start_reg, "grp_segmentIntersectsGri_fu_211_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_226_ap_start_reg, "grp_segmentIntersectsGri_fu_226_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_241_ap_start_reg, "grp_segmentIntersectsGri_fu_241_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_256_ap_start_reg, "grp_segmentIntersectsGri_fu_256_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_271_ap_start_reg, "grp_segmentIntersectsGri_fu_271_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_286_ap_start_reg, "grp_segmentIntersectsGri_fu_286_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_301_ap_start_reg, "grp_segmentIntersectsGri_fu_301_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_316_ap_start_reg, "grp_segmentIntersectsGri_fu_316_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_331_ap_start_reg, "grp_segmentIntersectsGri_fu_331_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_346_ap_start_reg, "grp_segmentIntersectsGri_fu_346_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_361_ap_start_reg, "grp_segmentIntersectsGri_fu_361_ap_start_reg");
    sc_trace(mVcdFile, grp_segmentIntersectsGri_fu_376_ap_start_reg, "grp_segmentIntersectsGri_fu_376_ap_start_reg");
    sc_trace(mVcdFile, grp_fu_391_p0, "grp_fu_391_p0");
    sc_trace(mVcdFile, zext_ln164_2_fu_421_p1, "zext_ln164_2_fu_421_p1");
    sc_trace(mVcdFile, or_ln164_fu_437_p2, "or_ln164_fu_437_p2");
    sc_trace(mVcdFile, zext_ln155_1_fu_450_p1, "zext_ln155_1_fu_450_p1");
    sc_trace(mVcdFile, shl_ln162_fu_454_p2, "shl_ln162_fu_454_p2");
    sc_trace(mVcdFile, zext_ln164_3_fu_467_p1, "zext_ln164_3_fu_467_p1");
    sc_trace(mVcdFile, shl_ln162_1_fu_470_p2, "shl_ln162_1_fu_470_p2");
    sc_trace(mVcdFile, zext_ln164_4_fu_483_p1, "zext_ln164_4_fu_483_p1");
    sc_trace(mVcdFile, shl_ln162_2_fu_486_p2, "shl_ln162_2_fu_486_p2");
    sc_trace(mVcdFile, or_ln164_2_fu_499_p2, "or_ln164_2_fu_499_p2");
    sc_trace(mVcdFile, zext_ln164_5_fu_504_p1, "zext_ln164_5_fu_504_p1");
    sc_trace(mVcdFile, shl_ln162_3_fu_508_p2, "shl_ln162_3_fu_508_p2");
    sc_trace(mVcdFile, zext_ln164_fu_442_p1, "zext_ln164_fu_442_p1");
    sc_trace(mVcdFile, add_ln164_1_fu_521_p2, "add_ln164_1_fu_521_p2");
    sc_trace(mVcdFile, zext_ln164_1_fu_446_p1, "zext_ln164_1_fu_446_p1");
    sc_trace(mVcdFile, shl_ln162_4_fu_531_p2, "shl_ln162_4_fu_531_p2");
    sc_trace(mVcdFile, or_ln164_3_fu_544_p2, "or_ln164_3_fu_544_p2");
    sc_trace(mVcdFile, zext_ln164_8_fu_553_p1, "zext_ln164_8_fu_553_p1");
    sc_trace(mVcdFile, shl_ln162_5_fu_557_p2, "shl_ln162_5_fu_557_p2");
    sc_trace(mVcdFile, zext_ln164_7_fu_549_p1, "zext_ln164_7_fu_549_p1");
    sc_trace(mVcdFile, add_ln164_2_fu_570_p2, "add_ln164_2_fu_570_p2");
    sc_trace(mVcdFile, zext_ln164_9_fu_576_p1, "zext_ln164_9_fu_576_p1");
    sc_trace(mVcdFile, shl_ln162_6_fu_580_p2, "shl_ln162_6_fu_580_p2");
    sc_trace(mVcdFile, or_ln164_4_fu_593_p2, "or_ln164_4_fu_593_p2");
    sc_trace(mVcdFile, zext_ln164_10_fu_598_p1, "zext_ln164_10_fu_598_p1");
    sc_trace(mVcdFile, shl_ln162_7_fu_602_p2, "shl_ln162_7_fu_602_p2");
    sc_trace(mVcdFile, or_ln164_5_fu_615_p2, "or_ln164_5_fu_615_p2");
    sc_trace(mVcdFile, zext_ln164_6_fu_527_p1, "zext_ln164_6_fu_527_p1");
    sc_trace(mVcdFile, shl_ln162_8_fu_624_p2, "shl_ln162_8_fu_624_p2");
    sc_trace(mVcdFile, add_ln164_3_fu_637_p2, "add_ln164_3_fu_637_p2");
    sc_trace(mVcdFile, zext_ln164_12_fu_643_p1, "zext_ln164_12_fu_643_p1");
    sc_trace(mVcdFile, shl_ln162_9_fu_647_p2, "shl_ln162_9_fu_647_p2");
    sc_trace(mVcdFile, add_ln164_4_fu_660_p2, "add_ln164_4_fu_660_p2");
    sc_trace(mVcdFile, zext_ln164_13_fu_666_p1, "zext_ln164_13_fu_666_p1");
    sc_trace(mVcdFile, shl_ln162_10_fu_670_p2, "shl_ln162_10_fu_670_p2");
    sc_trace(mVcdFile, add_ln164_5_fu_683_p2, "add_ln164_5_fu_683_p2");
    sc_trace(mVcdFile, zext_ln164_14_fu_689_p1, "zext_ln164_14_fu_689_p1");
    sc_trace(mVcdFile, shl_ln162_11_fu_693_p2, "shl_ln162_11_fu_693_p2");
    sc_trace(mVcdFile, zext_ln164_11_fu_620_p1, "zext_ln164_11_fu_620_p1");
    sc_trace(mVcdFile, shl_ln162_12_fu_706_p2, "shl_ln162_12_fu_706_p2");
    sc_trace(mVcdFile, or_ln164_6_fu_719_p2, "or_ln164_6_fu_719_p2");
    sc_trace(mVcdFile, zext_ln164_16_fu_728_p1, "zext_ln164_16_fu_728_p1");
    sc_trace(mVcdFile, shl_ln162_13_fu_732_p2, "shl_ln162_13_fu_732_p2");
    sc_trace(mVcdFile, zext_ln164_15_fu_724_p1, "zext_ln164_15_fu_724_p1");
    sc_trace(mVcdFile, add_ln164_6_fu_745_p2, "add_ln164_6_fu_745_p2");
    sc_trace(mVcdFile, zext_ln164_17_fu_751_p1, "zext_ln164_17_fu_751_p1");
    sc_trace(mVcdFile, shl_ln162_14_fu_755_p2, "shl_ln162_14_fu_755_p2");
    sc_trace(mVcdFile, or_ln164_7_fu_768_p2, "or_ln164_7_fu_768_p2");
    sc_trace(mVcdFile, zext_ln164_18_fu_773_p1, "zext_ln164_18_fu_773_p1");
    sc_trace(mVcdFile, shl_ln162_15_fu_777_p2, "shl_ln162_15_fu_777_p2");
    sc_trace(mVcdFile, select_ln161_fu_460_p3, "select_ln161_fu_460_p3");
    sc_trace(mVcdFile, select_ln161_1_fu_476_p3, "select_ln161_1_fu_476_p3");
    sc_trace(mVcdFile, select_ln161_2_fu_492_p3, "select_ln161_2_fu_492_p3");
    sc_trace(mVcdFile, select_ln161_3_fu_514_p3, "select_ln161_3_fu_514_p3");
    sc_trace(mVcdFile, or_ln161_1_fu_796_p2, "or_ln161_1_fu_796_p2");
    sc_trace(mVcdFile, or_ln161_fu_790_p2, "or_ln161_fu_790_p2");
    sc_trace(mVcdFile, select_ln161_4_fu_537_p3, "select_ln161_4_fu_537_p3");
    sc_trace(mVcdFile, select_ln161_5_fu_563_p3, "select_ln161_5_fu_563_p3");
    sc_trace(mVcdFile, select_ln161_6_fu_586_p3, "select_ln161_6_fu_586_p3");
    sc_trace(mVcdFile, select_ln161_7_fu_608_p3, "select_ln161_7_fu_608_p3");
    sc_trace(mVcdFile, or_ln161_4_fu_814_p2, "or_ln161_4_fu_814_p2");
    sc_trace(mVcdFile, or_ln161_3_fu_808_p2, "or_ln161_3_fu_808_p2");
    sc_trace(mVcdFile, or_ln161_5_fu_820_p2, "or_ln161_5_fu_820_p2");
    sc_trace(mVcdFile, or_ln161_2_fu_802_p2, "or_ln161_2_fu_802_p2");
    sc_trace(mVcdFile, select_ln161_8_fu_630_p3, "select_ln161_8_fu_630_p3");
    sc_trace(mVcdFile, select_ln161_9_fu_653_p3, "select_ln161_9_fu_653_p3");
    sc_trace(mVcdFile, select_ln161_10_fu_676_p3, "select_ln161_10_fu_676_p3");
    sc_trace(mVcdFile, select_ln161_11_fu_699_p3, "select_ln161_11_fu_699_p3");
    sc_trace(mVcdFile, or_ln161_8_fu_838_p2, "or_ln161_8_fu_838_p2");
    sc_trace(mVcdFile, or_ln161_7_fu_832_p2, "or_ln161_7_fu_832_p2");
    sc_trace(mVcdFile, select_ln161_12_fu_712_p3, "select_ln161_12_fu_712_p3");
    sc_trace(mVcdFile, select_ln161_13_fu_738_p3, "select_ln161_13_fu_738_p3");
    sc_trace(mVcdFile, select_ln161_14_fu_761_p3, "select_ln161_14_fu_761_p3");
    sc_trace(mVcdFile, select_ln161_15_fu_783_p3, "select_ln161_15_fu_783_p3");
    sc_trace(mVcdFile, or_ln161_11_fu_856_p2, "or_ln161_11_fu_856_p2");
    sc_trace(mVcdFile, or_ln161_10_fu_850_p2, "or_ln161_10_fu_850_p2");
    sc_trace(mVcdFile, or_ln161_12_fu_862_p2, "or_ln161_12_fu_862_p2");
    sc_trace(mVcdFile, or_ln161_9_fu_844_p2, "or_ln161_9_fu_844_p2");
    sc_trace(mVcdFile, or_ln161_13_fu_868_p2, "or_ln161_13_fu_868_p2");
    sc_trace(mVcdFile, or_ln161_6_fu_826_p2, "or_ln161_6_fu_826_p2");
    sc_trace(mVcdFile, or_ln161_14_fu_874_p2, "or_ln161_14_fu_874_p2");
    sc_trace(mVcdFile, sext_ln161_fu_880_p1, "sext_ln161_fu_880_p1");
    sc_trace(mVcdFile, icmp_ln155_fu_399_p2, "icmp_ln155_fu_399_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("honeybee.hdltvin.dat");
    mHdltvoutHandle.open("honeybee.hdltvout.dat");
}

honeybee::~honeybee() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_segmentIntersectsGri_fu_151;
    delete grp_segmentIntersectsGri_fu_166;
    delete grp_segmentIntersectsGri_fu_181;
    delete grp_segmentIntersectsGri_fu_196;
    delete grp_segmentIntersectsGri_fu_211;
    delete grp_segmentIntersectsGri_fu_226;
    delete grp_segmentIntersectsGri_fu_241;
    delete grp_segmentIntersectsGri_fu_256;
    delete grp_segmentIntersectsGri_fu_271;
    delete grp_segmentIntersectsGri_fu_286;
    delete grp_segmentIntersectsGri_fu_301;
    delete grp_segmentIntersectsGri_fu_316;
    delete grp_segmentIntersectsGri_fu_331;
    delete grp_segmentIntersectsGri_fu_346;
    delete grp_segmentIntersectsGri_fu_361;
    delete grp_segmentIntersectsGri_fu_376;
    delete honeybee_sitofp_3hbi_U62;
}

void honeybee::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_logic_1;
}

void honeybee::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_0;
}

void honeybee::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_3F800000;
}

void honeybee::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_40000000;
}

void honeybee::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv32_40400000;
}

void honeybee::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        b_0_reg_127 = b_fu_431_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        b_0_reg_127 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        collisions_0_reg_139 = or_ln161_15_fu_884_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        collisions_0_reg_139 = ap_const_lv64_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_151_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_151_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_151_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_151_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_166_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_166_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_166_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_166_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_181_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_181_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_181_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_181_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_196_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_196_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_196_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_196_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_211_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_211_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_211_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_211_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_226_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_226_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_226_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_226_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_241_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_241_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_241_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_241_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_256_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_256_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_256_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_256_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_271_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_271_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_271_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_271_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_286_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_286_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_286_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_286_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_301_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_301_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_301_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_301_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_316_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_316_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_316_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_316_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_331_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_331_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_331_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_331_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_346_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_346_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_346_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_346_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_361_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_361_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_361_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_361_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_segmentIntersectsGri_fu_376_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_segmentIntersectsGri_fu_376_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_segmentIntersectsGri_fu_376_ap_ready.read())) {
            grp_segmentIntersectsGri_fu_376_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        k_0_reg_116 = k_reg_1018.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_0_reg_116 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0))) {
        add_ln164_reg_1069 = add_ln164_fu_425_p2.read();
        or_ln164_1_reg_1059 = or_ln164_1_fu_415_p2.read();
        tmp_41_0_1_reg_1064 = grp_segmentIntersectsGri_fu_166_ap_return.read();
        tmp_41_0_2_reg_1074 = grp_segmentIntersectsGri_fu_181_ap_return.read();
        tmp_41_0_3_reg_1079 = grp_segmentIntersectsGri_fu_196_ap_return.read();
        tmp_41_1_1_reg_1089 = grp_segmentIntersectsGri_fu_226_ap_return.read();
        tmp_41_1_2_reg_1094 = grp_segmentIntersectsGri_fu_241_ap_return.read();
        tmp_41_1_3_reg_1099 = grp_segmentIntersectsGri_fu_256_ap_return.read();
        tmp_41_1_reg_1084 = grp_segmentIntersectsGri_fu_211_ap_return.read();
        tmp_41_2_1_reg_1109 = grp_segmentIntersectsGri_fu_286_ap_return.read();
        tmp_41_2_2_reg_1114 = grp_segmentIntersectsGri_fu_301_ap_return.read();
        tmp_41_2_3_reg_1119 = grp_segmentIntersectsGri_fu_316_ap_return.read();
        tmp_41_2_reg_1104 = grp_segmentIntersectsGri_fu_271_ap_return.read();
        tmp_41_3_1_reg_1129 = grp_segmentIntersectsGri_fu_346_ap_return.read();
        tmp_41_3_2_reg_1134 = grp_segmentIntersectsGri_fu_361_ap_return.read();
        tmp_41_3_3_reg_1139 = grp_segmentIntersectsGri_fu_376_ap_return.read();
        tmp_41_3_reg_1124 = grp_segmentIntersectsGri_fu_331_ap_return.read();
        tmp_s_reg_1054 = grp_segmentIntersectsGri_fu_151_ap_return.read();
        trunc_ln155_reg_1043 = trunc_ln155_fu_411_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grid_z_reg_1023 = grp_fu_391_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        k_reg_1018 = k_fu_405_p2.read();
    }
}

void honeybee::thread_add_ln164_1_fu_521_p2() {
    add_ln164_1_fu_521_p2 = (!ap_const_lv7_4.is_01() || !zext_ln164_fu_442_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_4) + sc_biguint<7>(zext_ln164_fu_442_p1.read()));
}

void honeybee::thread_add_ln164_2_fu_570_p2() {
    add_ln164_2_fu_570_p2 = (!ap_const_lv7_1.is_01() || !zext_ln164_7_fu_549_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(zext_ln164_7_fu_549_p1.read()));
}

void honeybee::thread_add_ln164_3_fu_637_p2() {
    add_ln164_3_fu_637_p2 = (!ap_const_lv7_5.is_01() || !zext_ln164_fu_442_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_5) + sc_biguint<7>(zext_ln164_fu_442_p1.read()));
}

void honeybee::thread_add_ln164_4_fu_660_p2() {
    add_ln164_4_fu_660_p2 = (!ap_const_lv7_6.is_01() || !zext_ln164_fu_442_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_6) + sc_biguint<7>(zext_ln164_fu_442_p1.read()));
}

void honeybee::thread_add_ln164_5_fu_683_p2() {
    add_ln164_5_fu_683_p2 = (!ap_const_lv7_7.is_01() || !zext_ln164_fu_442_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_7) + sc_biguint<7>(zext_ln164_fu_442_p1.read()));
}

void honeybee::thread_add_ln164_6_fu_745_p2() {
    add_ln164_6_fu_745_p2 = (!ap_const_lv7_1.is_01() || !zext_ln164_15_fu_724_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(zext_ln164_15_fu_724_p1.read()));
}

void honeybee::thread_add_ln164_fu_425_p2() {
    add_ln164_fu_425_p2 = (!ap_const_lv7_1.is_01() || !zext_ln164_2_fu_421_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(zext_ln164_2_fu_421_p1.read()));
}

void honeybee::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void honeybee::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void honeybee::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void honeybee::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void honeybee::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void honeybee::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void honeybee::thread_ap_block_state7_on_subcall_done() {
    ap_block_state7_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_151_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_166_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_181_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_196_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_211_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_226_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_241_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_256_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_271_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_286_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_301_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_316_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_331_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_346_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_361_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_segmentIntersectsGri_fu_376_ap_done.read()));
}

void honeybee::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln155_fu_399_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void honeybee::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void honeybee::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln155_fu_399_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void honeybee::thread_ap_return() {
    ap_return = collisions_0_reg_139.read();
}

void honeybee::thread_b_fu_431_p2() {
    b_fu_431_p2 = (!ap_const_lv7_10.is_01() || !b_0_reg_127.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_10) + sc_biguint<7>(b_0_reg_127.read()));
}

void honeybee::thread_grp_fu_391_p0() {
    grp_fu_391_p0 = esl_zext<32,3>(k_0_reg_116.read());
}

void honeybee::thread_grp_segmentIntersectsGri_fu_151_ap_start() {
    grp_segmentIntersectsGri_fu_151_ap_start = grp_segmentIntersectsGri_fu_151_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_166_ap_start() {
    grp_segmentIntersectsGri_fu_166_ap_start = grp_segmentIntersectsGri_fu_166_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_181_ap_start() {
    grp_segmentIntersectsGri_fu_181_ap_start = grp_segmentIntersectsGri_fu_181_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_196_ap_start() {
    grp_segmentIntersectsGri_fu_196_ap_start = grp_segmentIntersectsGri_fu_196_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_211_ap_start() {
    grp_segmentIntersectsGri_fu_211_ap_start = grp_segmentIntersectsGri_fu_211_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_226_ap_start() {
    grp_segmentIntersectsGri_fu_226_ap_start = grp_segmentIntersectsGri_fu_226_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_241_ap_start() {
    grp_segmentIntersectsGri_fu_241_ap_start = grp_segmentIntersectsGri_fu_241_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_256_ap_start() {
    grp_segmentIntersectsGri_fu_256_ap_start = grp_segmentIntersectsGri_fu_256_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_271_ap_start() {
    grp_segmentIntersectsGri_fu_271_ap_start = grp_segmentIntersectsGri_fu_271_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_286_ap_start() {
    grp_segmentIntersectsGri_fu_286_ap_start = grp_segmentIntersectsGri_fu_286_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_301_ap_start() {
    grp_segmentIntersectsGri_fu_301_ap_start = grp_segmentIntersectsGri_fu_301_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_316_ap_start() {
    grp_segmentIntersectsGri_fu_316_ap_start = grp_segmentIntersectsGri_fu_316_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_331_ap_start() {
    grp_segmentIntersectsGri_fu_331_ap_start = grp_segmentIntersectsGri_fu_331_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_346_ap_start() {
    grp_segmentIntersectsGri_fu_346_ap_start = grp_segmentIntersectsGri_fu_346_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_361_ap_start() {
    grp_segmentIntersectsGri_fu_361_ap_start = grp_segmentIntersectsGri_fu_361_ap_start_reg.read();
}

void honeybee::thread_grp_segmentIntersectsGri_fu_376_ap_start() {
    grp_segmentIntersectsGri_fu_376_ap_start = grp_segmentIntersectsGri_fu_376_ap_start_reg.read();
}

void honeybee::thread_icmp_ln155_fu_399_p2() {
    icmp_ln155_fu_399_p2 = (!k_0_reg_116.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_116.read() == ap_const_lv3_4);
}

void honeybee::thread_k_fu_405_p2() {
    k_fu_405_p2 = (!k_0_reg_116.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_0_reg_116.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void honeybee::thread_or_ln161_10_fu_850_p2() {
    or_ln161_10_fu_850_p2 = (select_ln161_12_fu_712_p3.read() | select_ln161_13_fu_738_p3.read());
}

void honeybee::thread_or_ln161_11_fu_856_p2() {
    or_ln161_11_fu_856_p2 = (select_ln161_14_fu_761_p3.read() | select_ln161_15_fu_783_p3.read());
}

void honeybee::thread_or_ln161_12_fu_862_p2() {
    or_ln161_12_fu_862_p2 = (or_ln161_11_fu_856_p2.read() | or_ln161_10_fu_850_p2.read());
}

void honeybee::thread_or_ln161_13_fu_868_p2() {
    or_ln161_13_fu_868_p2 = (or_ln161_12_fu_862_p2.read() | or_ln161_9_fu_844_p2.read());
}

void honeybee::thread_or_ln161_14_fu_874_p2() {
    or_ln161_14_fu_874_p2 = (or_ln161_13_fu_868_p2.read() | or_ln161_6_fu_826_p2.read());
}

void honeybee::thread_or_ln161_15_fu_884_p2() {
    or_ln161_15_fu_884_p2 = (collisions_0_reg_139.read() | sext_ln161_fu_880_p1.read());
}

void honeybee::thread_or_ln161_1_fu_796_p2() {
    or_ln161_1_fu_796_p2 = (select_ln161_2_fu_492_p3.read() | select_ln161_3_fu_514_p3.read());
}

void honeybee::thread_or_ln161_2_fu_802_p2() {
    or_ln161_2_fu_802_p2 = (or_ln161_1_fu_796_p2.read() | or_ln161_fu_790_p2.read());
}

void honeybee::thread_or_ln161_3_fu_808_p2() {
    or_ln161_3_fu_808_p2 = (select_ln161_4_fu_537_p3.read() | select_ln161_5_fu_563_p3.read());
}

void honeybee::thread_or_ln161_4_fu_814_p2() {
    or_ln161_4_fu_814_p2 = (select_ln161_6_fu_586_p3.read() | select_ln161_7_fu_608_p3.read());
}

void honeybee::thread_or_ln161_5_fu_820_p2() {
    or_ln161_5_fu_820_p2 = (or_ln161_4_fu_814_p2.read() | or_ln161_3_fu_808_p2.read());
}

void honeybee::thread_or_ln161_6_fu_826_p2() {
    or_ln161_6_fu_826_p2 = (or_ln161_5_fu_820_p2.read() | or_ln161_2_fu_802_p2.read());
}

void honeybee::thread_or_ln161_7_fu_832_p2() {
    or_ln161_7_fu_832_p2 = (select_ln161_8_fu_630_p3.read() | select_ln161_9_fu_653_p3.read());
}

void honeybee::thread_or_ln161_8_fu_838_p2() {
    or_ln161_8_fu_838_p2 = (select_ln161_10_fu_676_p3.read() | select_ln161_11_fu_699_p3.read());
}

void honeybee::thread_or_ln161_9_fu_844_p2() {
    or_ln161_9_fu_844_p2 = (or_ln161_8_fu_838_p2.read() | or_ln161_7_fu_832_p2.read());
}

void honeybee::thread_or_ln161_fu_790_p2() {
    or_ln161_fu_790_p2 = (select_ln161_fu_460_p3.read() | select_ln161_1_fu_476_p3.read());
}

void honeybee::thread_or_ln164_1_fu_415_p2() {
    or_ln164_1_fu_415_p2 = (trunc_ln155_fu_411_p1.read() | ap_const_lv6_1);
}

void honeybee::thread_or_ln164_2_fu_499_p2() {
    or_ln164_2_fu_499_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_3);
}

void honeybee::thread_or_ln164_3_fu_544_p2() {
    or_ln164_3_fu_544_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_5);
}

void honeybee::thread_or_ln164_4_fu_593_p2() {
    or_ln164_4_fu_593_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_7);
}

void honeybee::thread_or_ln164_5_fu_615_p2() {
    or_ln164_5_fu_615_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_C);
}

void honeybee::thread_or_ln164_6_fu_719_p2() {
    or_ln164_6_fu_719_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_D);
}

void honeybee::thread_or_ln164_7_fu_768_p2() {
    or_ln164_7_fu_768_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_F);
}

void honeybee::thread_or_ln164_fu_437_p2() {
    or_ln164_fu_437_p2 = (trunc_ln155_reg_1043.read() | ap_const_lv6_4);
}

void honeybee::thread_select_ln161_10_fu_676_p3() {
    select_ln161_10_fu_676_p3 = (!tmp_41_2_2_reg_1114.read()[0].is_01())? sc_lv<32>(): ((tmp_41_2_2_reg_1114.read()[0].to_bool())? shl_ln162_10_fu_670_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_11_fu_699_p3() {
    select_ln161_11_fu_699_p3 = (!tmp_41_2_3_reg_1119.read()[0].is_01())? sc_lv<32>(): ((tmp_41_2_3_reg_1119.read()[0].to_bool())? shl_ln162_11_fu_693_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_12_fu_712_p3() {
    select_ln161_12_fu_712_p3 = (!tmp_41_3_reg_1124.read()[0].is_01())? sc_lv<32>(): ((tmp_41_3_reg_1124.read()[0].to_bool())? shl_ln162_12_fu_706_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_13_fu_738_p3() {
    select_ln161_13_fu_738_p3 = (!tmp_41_3_1_reg_1129.read()[0].is_01())? sc_lv<32>(): ((tmp_41_3_1_reg_1129.read()[0].to_bool())? shl_ln162_13_fu_732_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_14_fu_761_p3() {
    select_ln161_14_fu_761_p3 = (!tmp_41_3_2_reg_1134.read()[0].is_01())? sc_lv<32>(): ((tmp_41_3_2_reg_1134.read()[0].to_bool())? shl_ln162_14_fu_755_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_15_fu_783_p3() {
    select_ln161_15_fu_783_p3 = (!tmp_41_3_3_reg_1139.read()[0].is_01())? sc_lv<32>(): ((tmp_41_3_3_reg_1139.read()[0].to_bool())? shl_ln162_15_fu_777_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_1_fu_476_p3() {
    select_ln161_1_fu_476_p3 = (!tmp_41_0_1_reg_1064.read()[0].is_01())? sc_lv<32>(): ((tmp_41_0_1_reg_1064.read()[0].to_bool())? shl_ln162_1_fu_470_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_2_fu_492_p3() {
    select_ln161_2_fu_492_p3 = (!tmp_41_0_2_reg_1074.read()[0].is_01())? sc_lv<32>(): ((tmp_41_0_2_reg_1074.read()[0].to_bool())? shl_ln162_2_fu_486_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_3_fu_514_p3() {
    select_ln161_3_fu_514_p3 = (!tmp_41_0_3_reg_1079.read()[0].is_01())? sc_lv<32>(): ((tmp_41_0_3_reg_1079.read()[0].to_bool())? shl_ln162_3_fu_508_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_4_fu_537_p3() {
    select_ln161_4_fu_537_p3 = (!tmp_41_1_reg_1084.read()[0].is_01())? sc_lv<32>(): ((tmp_41_1_reg_1084.read()[0].to_bool())? shl_ln162_4_fu_531_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_5_fu_563_p3() {
    select_ln161_5_fu_563_p3 = (!tmp_41_1_1_reg_1089.read()[0].is_01())? sc_lv<32>(): ((tmp_41_1_1_reg_1089.read()[0].to_bool())? shl_ln162_5_fu_557_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_6_fu_586_p3() {
    select_ln161_6_fu_586_p3 = (!tmp_41_1_2_reg_1094.read()[0].is_01())? sc_lv<32>(): ((tmp_41_1_2_reg_1094.read()[0].to_bool())? shl_ln162_6_fu_580_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_7_fu_608_p3() {
    select_ln161_7_fu_608_p3 = (!tmp_41_1_3_reg_1099.read()[0].is_01())? sc_lv<32>(): ((tmp_41_1_3_reg_1099.read()[0].to_bool())? shl_ln162_7_fu_602_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_8_fu_630_p3() {
    select_ln161_8_fu_630_p3 = (!tmp_41_2_reg_1104.read()[0].is_01())? sc_lv<32>(): ((tmp_41_2_reg_1104.read()[0].to_bool())? shl_ln162_8_fu_624_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_9_fu_653_p3() {
    select_ln161_9_fu_653_p3 = (!tmp_41_2_1_reg_1109.read()[0].is_01())? sc_lv<32>(): ((tmp_41_2_1_reg_1109.read()[0].to_bool())? shl_ln162_9_fu_647_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_select_ln161_fu_460_p3() {
    select_ln161_fu_460_p3 = (!tmp_s_reg_1054.read()[0].is_01())? sc_lv<32>(): ((tmp_s_reg_1054.read()[0].to_bool())? shl_ln162_fu_454_p2.read(): ap_const_lv32_0);
}

void honeybee::thread_sext_ln161_fu_880_p1() {
    sext_ln161_fu_880_p1 = esl_sext<64,32>(or_ln161_14_fu_874_p2.read());
}

void honeybee::thread_shl_ln162_10_fu_670_p2() {
    shl_ln162_10_fu_670_p2 = (!zext_ln164_13_fu_666_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_13_fu_666_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_11_fu_693_p2() {
    shl_ln162_11_fu_693_p2 = (!zext_ln164_14_fu_689_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_14_fu_689_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_12_fu_706_p2() {
    shl_ln162_12_fu_706_p2 = (!zext_ln164_11_fu_620_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_11_fu_620_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_13_fu_732_p2() {
    shl_ln162_13_fu_732_p2 = (!zext_ln164_16_fu_728_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_16_fu_728_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_14_fu_755_p2() {
    shl_ln162_14_fu_755_p2 = (!zext_ln164_17_fu_751_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_17_fu_751_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_15_fu_777_p2() {
    shl_ln162_15_fu_777_p2 = (!zext_ln164_18_fu_773_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_18_fu_773_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_1_fu_470_p2() {
    shl_ln162_1_fu_470_p2 = (!zext_ln164_3_fu_467_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_3_fu_467_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_2_fu_486_p2() {
    shl_ln162_2_fu_486_p2 = (!zext_ln164_4_fu_483_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_4_fu_483_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_3_fu_508_p2() {
    shl_ln162_3_fu_508_p2 = (!zext_ln164_5_fu_504_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_5_fu_504_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_4_fu_531_p2() {
    shl_ln162_4_fu_531_p2 = (!zext_ln164_1_fu_446_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_1_fu_446_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_5_fu_557_p2() {
    shl_ln162_5_fu_557_p2 = (!zext_ln164_8_fu_553_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_8_fu_553_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_6_fu_580_p2() {
    shl_ln162_6_fu_580_p2 = (!zext_ln164_9_fu_576_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_9_fu_576_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_7_fu_602_p2() {
    shl_ln162_7_fu_602_p2 = (!zext_ln164_10_fu_598_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_10_fu_598_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_8_fu_624_p2() {
    shl_ln162_8_fu_624_p2 = (!zext_ln164_6_fu_527_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_6_fu_527_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_9_fu_647_p2() {
    shl_ln162_9_fu_647_p2 = (!zext_ln164_12_fu_643_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln164_12_fu_643_p1.read().to_uint();
}

void honeybee::thread_shl_ln162_fu_454_p2() {
    shl_ln162_fu_454_p2 = (!zext_ln155_1_fu_450_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_1 << (unsigned short)zext_ln155_1_fu_450_p1.read().to_uint();
}

void honeybee::thread_trunc_ln155_fu_411_p1() {
    trunc_ln155_fu_411_p1 = b_0_reg_127.read().range(6-1, 0);
}

void honeybee::thread_zext_ln155_1_fu_450_p1() {
    zext_ln155_1_fu_450_p1 = esl_zext<32,7>(b_0_reg_127.read());
}

void honeybee::thread_zext_ln164_10_fu_598_p1() {
    zext_ln164_10_fu_598_p1 = esl_zext<32,6>(or_ln164_4_fu_593_p2.read());
}

void honeybee::thread_zext_ln164_11_fu_620_p1() {
    zext_ln164_11_fu_620_p1 = esl_zext<32,6>(or_ln164_5_fu_615_p2.read());
}

void honeybee::thread_zext_ln164_12_fu_643_p1() {
    zext_ln164_12_fu_643_p1 = esl_zext<32,7>(add_ln164_3_fu_637_p2.read());
}

void honeybee::thread_zext_ln164_13_fu_666_p1() {
    zext_ln164_13_fu_666_p1 = esl_zext<32,7>(add_ln164_4_fu_660_p2.read());
}

void honeybee::thread_zext_ln164_14_fu_689_p1() {
    zext_ln164_14_fu_689_p1 = esl_zext<32,7>(add_ln164_5_fu_683_p2.read());
}

void honeybee::thread_zext_ln164_15_fu_724_p1() {
    zext_ln164_15_fu_724_p1 = esl_zext<7,6>(or_ln164_6_fu_719_p2.read());
}

void honeybee::thread_zext_ln164_16_fu_728_p1() {
    zext_ln164_16_fu_728_p1 = esl_zext<32,6>(or_ln164_6_fu_719_p2.read());
}

void honeybee::thread_zext_ln164_17_fu_751_p1() {
    zext_ln164_17_fu_751_p1 = esl_zext<32,7>(add_ln164_6_fu_745_p2.read());
}

void honeybee::thread_zext_ln164_18_fu_773_p1() {
    zext_ln164_18_fu_773_p1 = esl_zext<32,6>(or_ln164_7_fu_768_p2.read());
}

void honeybee::thread_zext_ln164_1_fu_446_p1() {
    zext_ln164_1_fu_446_p1 = esl_zext<32,6>(or_ln164_fu_437_p2.read());
}

void honeybee::thread_zext_ln164_2_fu_421_p1() {
    zext_ln164_2_fu_421_p1 = esl_zext<7,6>(or_ln164_1_fu_415_p2.read());
}

void honeybee::thread_zext_ln164_3_fu_467_p1() {
    zext_ln164_3_fu_467_p1 = esl_zext<32,6>(or_ln164_1_reg_1059.read());
}

void honeybee::thread_zext_ln164_4_fu_483_p1() {
    zext_ln164_4_fu_483_p1 = esl_zext<32,7>(add_ln164_reg_1069.read());
}

void honeybee::thread_zext_ln164_5_fu_504_p1() {
    zext_ln164_5_fu_504_p1 = esl_zext<32,6>(or_ln164_2_fu_499_p2.read());
}

void honeybee::thread_zext_ln164_6_fu_527_p1() {
    zext_ln164_6_fu_527_p1 = esl_zext<32,7>(add_ln164_1_fu_521_p2.read());
}

void honeybee::thread_zext_ln164_7_fu_549_p1() {
    zext_ln164_7_fu_549_p1 = esl_zext<7,6>(or_ln164_3_fu_544_p2.read());
}

void honeybee::thread_zext_ln164_8_fu_553_p1() {
    zext_ln164_8_fu_553_p1 = esl_zext<32,6>(or_ln164_3_fu_544_p2.read());
}

void honeybee::thread_zext_ln164_9_fu_576_p1() {
    zext_ln164_9_fu_576_p1 = esl_zext<32,7>(add_ln164_2_fu_570_p2.read());
}

void honeybee::thread_zext_ln164_fu_442_p1() {
    zext_ln164_fu_442_p1 = esl_zext<7,6>(or_ln164_fu_437_p2.read());
}

void honeybee::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln155_fu_399_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

void honeybee::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p1_x\" :  \"" << edge_p1_x.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p1_y\" :  \"" << edge_p1_y.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p1_z\" :  \"" << edge_p1_z.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p2_x\" :  \"" << edge_p2_x.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p2_y\" :  \"" << edge_p2_y.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"edge_p2_z\" :  \"" << edge_p2_z.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

